### ISSUE TITLE
vlan4000 device

### ISSUE THREAD

**Issue by jahanson** [ariadata/proxmox-hetzner#1]
Is the device supposed to be vlan4000? Or should it be vmbr0?
https://github.com/ariadata/proxmox-hetzner/blob/7be33be22bc33de9ec9ee47a3a3dab79235c3640/README.md?plain=1#L182

**Comment by pcmehrdad** [comment]
No that should be `vlan`+`VLAN_ID`
according to this link:
https://docs.hetzner.com/robot/dedicated-server/network/vswitch/
vlan_id must be between 4000 to 4091

if your VLAN_ID number is 4052 this must be `vlan4052`.

please consider to read this link too:
https://docs.hetzner.com/cloud/networks/connect-dedi-vswitch/

**Comment by jahanson** [comment]
Thank you!
