### ISSUE TITLE
Link not working 404 NOT FOUND

### ISSUE THREAD

**Issue by joyshmitz** [ariadata/proxmox-hetzner#3]
[README v2](https://github.com/ariadata/proxmox-hetzner/blob/main/README-v2.md#use-config-generator-to-make-basic-configurations)
https://neo-work.ariadata.co/tools/proxmox-hetzner-config-generator
404 NOT FOUND

**Comment by pcmehrdad** [comment]
It is not stable, so sorry we have to rename this file.
